name: Restraint
views:
    Night:
        T: 6500
        Lsw: 2
        Lmax: 10
        Lb: 6
        bg_hex: "#e8e8e8"
    Day:
        T: 6500
        Lsw: 100
        Lmax: 60
        Lb: 40
        bg_hex: "#e8e8e8"
palette:
    greys:
        type: fixed
        args:
            black: "#000000"
            white: "#ffffff"
            fg_dark: "#202020"
            fg: "#3d3d3d"
            fg_light: "#707070"
            bg: "#e8e8e8"
            bg_dark: "#d9d9d9"
            bg_darker: "#d2d2d2"
    salmon:
        type: fixed
        args:
            salmon_dark: "#CCC1B7"
            salmon: "#F2DFCE"
            salmon_light: "#FFF1E4"
    ult:
        type: jab_ring
        args:
            n_colors: 6
            m_lb: 27.0
            m_ub: 27.0
            j_lb: 0.54
            j_ub: 0.54
    pri:
        type: jab_ring
        args:
            n_colors: 8
            m_lb: 18.0
            m_ub: 18.0
            j_lb: 0.44
            j_ub: 0.44
            hue_offset: 0.3
    tone:
        type: jab_ring
        args:
            n_colors: 6
            j_lb: 0.305
            j_ub: 0.305
            m_lb: 13.0
            m_ub: 13.0
            hue_offset: 0.5
    snd:
        type: jab_ring
        args:
            n_colors: 4
            j_lb: 0.47
            j_ub: 0.47
            m_lb: 5.0
            m_ub: 5.0
            hue_offset: 0.8
    shd:
        type: jab_ring
        args:
            n_colors: 8
            j_lb: 0.75
            j_ub: 0.75
            m_lb: 3.5
            m_ub: 3.5
    hl:
        type: jab_ring
        args:
            n_colors: 8
            j_lb: 0.84
            j_ub: 0.84
            m_lb: 11.5
            m_ub: 11.5
    bg:
        type: jab_ring
        args:
            n_colors: 8
            j_lb: 0.89
            j_ub: 0.89
            m_lb: 5.0
            m_ub: 5.0
