name: Restraint
views:
    Night:
        T: 6000
        Lsw: 2
        Lmax: 10
        Lb: 6
        bg_hex: "#ECE6DD"
    Day:
        T: 7000
        Lsw: 100
        Lmax: 60
        Lb: 40
        bg_hex: "#e8e8e8"
palette:
    greys:
        type: greys
        args:
            white: 0.97
            bg_light: 0.92
            bg: 0.90
            bg_dark: &j_bg_dark 0.80
            fg_light: 0.35
            fg: 0.15
            fg_dark: 0.07
            black: 0.00
    salmon:
        type: fixed
        args:
            salmon_dark: "#CCC1B7"
            salmon: "#F2DFCE"
            salmon_light: "#FFF1E4"
    pri:
        type: tri_hex
        args:
            base_j: 0.26
            pitch: 0.13
            j_scale: 0.80
            # this is a very specific value to minimize blue oversaturation on 6500k sRGB
            # the Jab'p cone has a "crease" at rgb=(0, 0, x) which we want to be maximally
            # far from. It just happens to be zero.
            first_ring_offset: 0.0
            ring0_name: tone
            ring1_name: pri
            ring2_name: ult
            tints_name: tint
    shd:
        type: jab_ring
        args:
            n_colors: 8
            j_lb: 0.7
            j_ub: 0.7
            m_lb: 3
            m_ub: 3
    hl:
        type: jab_ring
        args:
            n_colors: 8
            j_lb: 0.77
            j_ub: 0.77
            m_lb: 11.5
            m_ub: 11.5
            hue_offset: &lights_offset 0.2
    bg:
        type: jab_ring
        args:
            n_colors: 8
            j_lb: *j_bg_dark
            j_ub: *j_bg_dark
            m_lb: 4.0
            m_ub: 4.0
            hue_offset: *lights_offset
    wht:
        type: jab_ring
        args:
            n_colors: 8
            j_lb: 0.885
            j_ub: 0.885
            m_lb: 3.0
            m_ub: 3.0
            hue_offset: *lights_offset
